---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress-but-dns-and-proxy
  namespace: measurement
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          run: squid-proxy
    ports:
      - port: 3128
        protocol: UDP
      - port: 3128
        protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: proxy-allow-egress
  namespace: measurement
spec:
  podSelector:
    matchLabels:
      run: squid-proxy
  policyTypes:
  - Egress
  egress:
  - {}


---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: squid-proxy
  name: squid-proxy
  namespace: measurement
spec:
  containers:
  - image: ubuntu/squid:5.2-22.04_beta
    name: squid-proxy
    ports: 
    - containerPort: 3128
    env:
    - name: TZ
      value: UTC

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: squid-proxy
  name: squid-proxy
  namespace: measurement
spec:
  ports:
  - port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    run: squid-proxy