---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: squid-proxy
  name: squid-proxy
  namespace: measurement
spec:
  containers:
  - image: ubuntu/squid:5.2-22.04_beta
    name: squid-proxy
    ports: 
    - containerPort: 3128
    env:
    - name: TZ
      value: UTC

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: squid-proxy
  name: squid-proxy
  namespace: measurement
spec:
  ports:
  - port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    run: squid-proxy